import {catalog,categories,filterProjects} from './catalog.js';
import {trendingCatalog} from './trending-catalog.js';
import {openCatalog} from './open-catalog.js';
const main=document.querySelector('#main');
const paths={
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
 moon:'<path d="M20.5 13A9 9 0 0 1 11 3.5 9 9 0 1 0 20.5 13Z"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/>',
 github:'<path d="M9 19c-4.5 1.3-4.5-2.2-6.3-2.6M15 22v-3.9a3.4 3.4 0 0 0-.9-2.6c3-.4 6.2-1.5 6.2-6.7a5.2 5.2 0 0 0-1.4-3.6 4.8 4.8 0 0 0-.1-3.6s-1.2-.4-3.8 1.4a13 13 0 0 0-6.8 0C5.6 1.2 4.4 1.6 4.4 1.6a4.8 4.8 0 0 0-.1 3.6A5.2 5.2 0 0 0 2.9 9c0 5.2 3.1 6.3 6.2 6.7a3.4 3.4 0 0 0-.9 2.5V22"/>',
 arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',chevron:'<path d="m9 5 7 7-7 7"/>',back:'<path d="m14 5-7 7 7 7"/>',external:'<path d="M14 3h7v7m0-7L10 14M10 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5"/>',
 star:'<path d="m12 3 2.8 5.8 6.4.9-4.6 4.5 1.1 6.3-5.7-3-5.7 3 1.1-6.3-4.6-4.5 6.4-.9z"/>',
 sparkles:'<path d="m12 3 2.2 6.8L21 12l-6.8 2.2L12 21l-2.2-6.8L3 12l6.8-2.2L12 3ZM20 2v4m-2-2h4M4 18v4m-2-2h4"/>',
 code:'<path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/>',
 pen:'<path d="m16 3 5 5-11 11-7 2 2-7L16 3Zm-3 3 5 5M3 21l4-4"/>',
 video:'<rect x="3" y="5" width="14" height="14" rx="3"/><path d="m17 9 5-3v12l-5-3"/>',
 layers:'<path d="m12 3 10 6-10 6L2 9l10-6Zm-10 12 10 6 10-6M2 12l10 6 10-6"/>',
 wallet:'<path d="M20 8V5a2 2 0 0 0-2-2H5a3 3 0 0 0 0 6h15v12H5a3 3 0 0 1-3-3V6m18 7h-5v4h5"/><path d="M16 15h1"/>',
 heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
 shield:'<path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Z"/><path d="m8 12 3 3 5-6"/>',
 sliders:'<path d="M4 4v4m0 5v7M12 4v9m0 5v2M20 4v2m0 5v9"/><path d="M1 8h6v5H1zM9 13h6v5H9zM17 6h6v5h-6z"/>',
 terminal:'<rect x="2" y="3" width="20" height="18" rx="3"/><path d="m6 8 4 4-4 4m7 0h5"/>',
 scissors:'<circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><path d="m8.5 7.5 13 13m-13-4 13-13M12 12l-3-3"/>',
 hands:'<path d="m6 12-3-3a2 2 0 0 0-1 3l5 8h4V8a2 2 0 0 0-4 0v6M18 12l3-3a2 2 0 0 1 1 3l-5 8h-4V8a2 2 0 0 1 4 0v6M6 2l2 2m10-2-2 2M12 1v3"/>',
 chat:'<path d="M21 11a8 8 0 0 1-8 8H6l-5 3 2-6a8 8 0 0 1-1-5 9 9 0 0 1 19 0Z"/><path d="M7 10h10M7 14h6"/>',
 project:'<path d="M3 4h5v5H3zM14 4h7v5h-7zM3 15h7v5H3zM16 15h5v5h-5zM8 6h6M6 9v6m4 2h6M18 9v6"/>',
 tofu:'<path d="m3 7 9-4 9 4v11l-9 4-9-4V7Zm0 0 9 4 9-4M12 11v11M7 12v3m10-3v3M10 17h4"/>',
 observe:'<circle cx="10" cy="10" r="7"/><path d="m15 15 7 7M6 10l3 3 5-6"/>',
 refine:'<path d="M4 3h16v4l-6 6v6l-4 2v-8L4 7V3Z"/>',
 board:'<rect x="2" y="3" width="20" height="15" rx="2"/><path d="M8 23l4-5 4 5M6 8h9m-9 5h12"/>',
 speed:'<path d="M3 19a10 10 0 1 1 18 0M4 11l2 1m2-7 1 2m7-2-1 2m5 4-2 1M12 16l4-7"/><circle cx="12" cy="16" r="2"/>',
 penpot:'<path d="m3 8 9-5 9 5v9l-9 5-9-5V8Zm0 0 9 5 9-5M12 13v9M7 5l10 6v4"/>',
 flow:'<path d="M3 6c6-8 8 8 12 4s6-7 7-4M3 14c6-8 8 8 12 4s6-7 7-4"/>',
 film:'<rect x="2" y="3" width="20" height="18" rx="3"/><path d="M7 3v18m10-18v18M2 8h5M2 16h5M17 8h5m-5 8h5m-12-6 5 3-5 3v-6Z"/>',
 audio:'<path d="M3 10v4m4-8v12m5-16v20m5-16v12m4-8v4"/>',
 server:'<rect x="3" y="3" width="18" height="7" rx="2"/><rect x="3" y="14" width="18" height="7" rx="2"/><path d="M7 6.5h.01M7 17.5h.01M12 7h5m-5 11h5"/>',
 download:'<path d="M12 2v13m-5-5 5 5 5-5M3 16v4a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-4"/>',
 paperclip:'<path d="m8 12 7-7a4 4 0 0 1 6 6L10 22a6 6 0 0 1-8-8L13 3a2 2 0 0 1 3 3L6 16"/>',
 check:'<path d="m4 12 5 5L20 6"/>',fork:'<circle cx="6" cy="4" r="2"/><circle cx="18" cy="4" r="2"/><circle cx="12" cy="20" r="2"/><path d="M6 6v4c0 3 6 2 6 6v2M18 6v4c0 3-6 2-6 6"/>',
 globe:'<circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a18 18 0 0 1 0 20 18 18 0 0 1 0-20Z"/>',
 bookmark:'<path d="M5 3h14v19l-7-5-7 5V3Z"/>',info:'<circle cx="12" cy="12" r="10"/><path d="M12 11v6m0-10h.01"/>'
};
const svg=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.layers}</svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const compact=n=>n==null?'—':new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(n);
const exact=n=>n==null?'Unavailable':new Intl.NumberFormat('en').format(n);
const date=value=>value?new Intl.DateTimeFormat('en',{month:'short',day:'numeric',year:'numeric'}).format(new Date(value)):'Unavailable';
const gh=p=>`https://github.com/${p.repo}`;
const appLink=p=>`#/app/${p.id}`;
const externalAttrs='target="_blank" rel="noopener noreferrer"';
let projects=[...catalog,...openCatalog,...trendingCatalog],snapshot={},trendSnapshot={},assetSources={},officialIcons={},reviewSnapshot={};
let visibleLimit=24,lastResultKey='';
let toastTimer;
let saved;
try {saved=new Set(JSON.parse(localStorage.getItem('openstore-saved')||'[]'));} catch {saved=new Set();}
function icon(p){
 const asset=officialIcons[p.id];
 return `<span class="app-icon image-icon" title="Official ${esc(p.name)} project icon"><img src="assets/${esc(asset.file)}" alt="" loading="lazy" width="53" height="53"></span>`;
}
function rating(p){const r=p.review;return r?`<a class="review-rating" href="${esc(r.url)}" ${externalAttrs} title="${esc(r.provider)} user rating, captured ${date(r.capturedAt)}">${svg('star')}<strong>${r.rating.toFixed(1)}</strong><span>${exact(r.count)} reviews · ${esc(r.provider)}</span></a>`:'';}
function reviewCard(p){if(!p.review)return row(p);return `<article class="review-card"><a class="review-app" href="${appLink(p)}">${icon(p)}<div><h3>${esc(p.name)}</h3><p>${esc(p.bestFor||p.review.useCase)}</p></div>${svg('chevron')}</a>${rating(p)}<p class="review-summary">${esc(p.review.summary)}</p>${p.review.feedbackUrl?`<a class="text-link feedback-source" href="${esc(p.review.feedbackUrl)}" ${externalAttrs}>Feedback notes · ${esc(p.review.feedbackProvider)} ${svg('external')}</a>`:''}<div class="review-card-foot"><span>${svg('star')}${compact(p.stars)} GitHub stars</span><a href="${appLink(p)}" class="text-link">Explore app ${svg('chevron')}</a></div></article>`;}
function evidence(p){return `<section class="selection-panel"><div class="selection-title"><span class="eyebrow">FIND YOUR FIT</span><h2>A good fit for ${esc((p.bestFor||p.description.replace(/\.$/,''))[0].toLowerCase()+(p.bestFor||p.description.replace(/\.$/,'')).slice(1))}.</h2></div>${p.consideration?`<p class="fit-consideration">${esc(p.consideration)}</p>`:''}<div class="feedback-panel"><div><h3>User feedback</h3>${p.review?rating(p):'<span class="unrated">No aggregate rating verified</span>'}</div><p>${p.review?esc(p.review.summary):'Explore discussions, issues, and documentation to see how this project fits your workflow.'}</p><div class="feedback-links">${p.review?`<a class="text-link" href="${esc(p.review.url)}" ${externalAttrs}>Read reviews ${svg('external')}</a><span>${p.review.smallSample?'Small sample · ':''}Captured ${date(p.review.capturedAt)}</span>`:`<a class="text-link" href="${gh(p)}/discussions" ${externalAttrs}>Community discussions ${svg('external')}</a>`}${p.review?.feedbackUrl?`<a class="text-link" href="${esc(p.review.feedbackUrl)}" ${externalAttrs}>Feedback notes · ${esc(p.review.feedbackProvider)} ${svg('external')}</a>`:''}<a class="text-link" href="${gh(p)}/issues" ${externalAttrs}>Project issues ${svg('external')}</a></div><p class="review-context">${p.review?'Product-level ratings can include hosted and paid editions. ':''}GitHub stars measure repository interest, not customer satisfaction.</p></div></section>`;}
function sourceBadge(p){return p.sourceAvailable?'<span class="source-badge">SOURCE-AVAILABLE</span>':'';}
function row(p){return `<article class="app-row"><a href="${appLink(p)}" aria-label="Explore ${esc(p.name)}">${icon(p)}</a><div class="app-copy"><h3><a href="${appLink(p)}">${esc(p.name)}</a>${sourceBadge(p)}</h3><p>${esc(p.description)}</p><div class="replace-label">Alternative to <b>${esc(p.replaces[0])}</b></div><div class="app-meta"><span class="stars" title="${exact(p.stars)} GitHub stars as of ${date(snapshot.fetchedAt)}">${svg('star')}${compact(p.stars)}</span><span class="divider">·</span><a href="#/browse?category=${encodeURIComponent(p.category)}">${esc(p.category)}</a><span class="divider">·</span><span class="platform">${p.platforms.includes('Web')?'Web':p.platforms[0]}</span>${p.weeklyStars?`<span class="trend-badge" title="GitHub weekly stars as of ${date(trendSnapshot.fetchedAt)}">↗ ${compact(p.weeklyStars)} this week</span>`:''}</div></div><a class="app-github" href="${gh(p)}" ${externalAttrs} aria-label="${esc(p.name)} on GitHub">${svg('github')}</a></article>`;}
function card(p){return `<article class="catalog-card"><div class="catalog-card-top"><a href="${appLink(p)}" aria-label="Explore ${esc(p.name)}">${icon(p)}</a><div class="catalog-identity"><h3><a href="${appLink(p)}">${esc(p.name)}</a></h3><p>${esc(p.category)}</p></div><a class="app-github" href="${gh(p)}" ${externalAttrs} aria-label="${esc(p.name)} on GitHub">${svg('github')}</a></div><p class="catalog-description" title="${esc(p.description)}">${esc(p.description)}</p><div class="replacement-chip"><span>Alternative to</span><b>${esc(p.replaces[0])}</b></div><div class="card-fit"><span>Best for</span><p title="${esc(p.bestFor)}">${esc(p.bestFor)}</p></div><div class="card-evidence"><span class="github-stat" title="${exact(p.stars)} GitHub stars">${svg('github')}<strong>${compact(p.stars)}</strong><span>GitHub stars</span>${p.weeklyStars?`<span class="trend-badge">↗ ${compact(p.weeklyStars)} / week</span>`:''}</span>${rating(p)}</div><div class="card-platforms">${svg('globe')}<span>${esc(p.platforms.join(' · '))}</span></div><div class="catalog-card-bottom"><div class="card-badges">${p.selfHosted?'<span class="selfhost-tag">Self-hosted</span>':''}${sourceBadge(p)}</div><a href="${appLink(p)}" class="card-action">View app ${svg('arrow')}</a></div></article>`;}

function heading(title,subtitle,link,label='See all',glyph=''){return `<div class="section-heading"><div><h2>${glyph?svg(glyph):''}${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div>${link?`<a class="text-link" href="${link}">${label} ${svg('chevron')}</a>`:''}</div>`;}
function searchBox(query=''){return `<div class="search-box">${svg('search')}<input type="search" id="app-search" aria-label="Search open-source alternatives" placeholder="Search open-source alternatives…" autocomplete="off" value="${esc(query)}">${query?'<button class="search-clear" data-action="clear-search" aria-label="Clear search">×</button>':'<kbd>⌘ K</kbd>'}</div>`;}
function categoryCard(c,directory=false){const count=projects.filter(p=>p.category===c.name).length;return `<a class="category-card" href="#/browse?category=${encodeURIComponent(c.name)}" style="--category-color:${c.color}">${svg(c.icon)}<div><span>${esc(c.name)}</span>${directory?`<p>${count} curated ${count===1?'app':'apps'} ${count?'→':''}</p>`:''}</div></a>`;}
function featureArtwork(style){const file=style==='cut'?'video':style;return `<div class="promo-visual" aria-hidden="true"><img src="assets/promo-${file}.svg" alt="" width="400" height="240"></div>`;}
function heroApp(p,index){return `<a class="hero-app hero-app-${index}" href="${appLink(p)}" aria-label="Explore ${esc(p.name)}"><div class="hero-app-icon">${icon(p)}</div><h2>${esc(p.name)}</h2><p>Alternative to ${esc(p.replaces[0])}</p><div class="hero-app-bottom"><span title="${exact(p.stars)} GitHub stars · ${date(snapshot.fetchedAt)}">${svg('star')}<strong>${compact(p.stars)}</strong><small>GitHub stars</small></span><span class="hero-app-arrow">${svg('arrow')}</span></div></a>`;}
function discoveryHero(){const picks=['kdenlive','actual','opencode','penpot','opencut','openhands','bitwarden'];return `<section class="intro hero-intro discovery-hero" aria-labelledby="discovery-title"><div class="hero-orbits" aria-hidden="true"></div><div class="hero-heading"><div class="hero-label"><span class="eyebrow">THE OPEN-SOURCE APP STORE</span><span class="hero-label-divider" aria-hidden="true"></span><span class="hero-count">${projects.length} curated apps</span></div><h1 id="discovery-title">The best of open source<span>all in one place.</span></h1><p>Discover beautifully designed, community-built alternatives<br class="hero-desktop-break"> to the apps you use every day.</p><div class="hero-search-area">${searchBox()}</div><nav class="hero-categories" aria-label="Discover apps by category"><a class="selected" href="#/browse">All apps</a>${['AI','Developer Tools','Design','Productivity','Video','Privacy'].map(name=>{const c=categories.find(c=>c.name===name);return `<a href="#/browse?category=${encodeURIComponent(name)}">${svg(c.icon)}${esc(name)}</a>`;}).join('')}<a href="#/categories">More ${svg('chevron')}</a></nav></div><div class="hero-showcase" aria-label="Featured open-source alternatives"><div class="hero-apps">${picks.map((id,i)=>heroApp(projects.find(p=>p.id===id),i)).join('')}</div></div><div class="hero-values">${[['penpot','Curated with care','Thoughtfully chosen open-source apps.'],['hands','Community driven','Built and maintained by real people.'],['shield','More control','Open tools. Your own possibilities.']].map(([glyph,title,copy])=>`<div>${svg(glyph)}<div><strong>${title}</strong><p>${copy}</p></div></div>`).join('')}</div><div class="popular-searches"><span>Looking to replace?</span><div class="replacement-suggestions">${['Notion','Figma','CapCut','ChatGPT'].map(name=>`<button data-search="${name}">${name} ${svg('arrow')}</button>`).join('')}</div></div></section>`;}
function home(){const find=id=>projects.find(p=>p.id===id);const code=find('opencode'),cut=find('opencut'),pen=find('penpot');const trending=projects.filter(p=>p.trending).sort((a,b)=>b.weeklyStars-a.weeklyStars).slice(0,6);return `
${discoveryHero()}

<section class="section">${heading('Made to be yours.','Handpicked software. A little more freedom.','#/browse','Explore all apps')}<div class="feature-grid">
${[[code,'code','THE DEVELOPER’S PICK','Your next coding companion.','Meet OpenCode. Make something great.'],[cut,'cut','CREATIVITY, UNCUT','Your story. Your editor.','Create without the subscription.'],[pen,'design','DESIGN WITHOUT LIMITS','Good design. Open by design.','A canvas for your next idea.']].map(([p,style,label,title,tagline])=>`<a class="feature feature-${style}" href="${appLink(p)}"><div class="feature-art"><span class="eyebrow">${label}</span><h3>${title}</h3><p class="feature-tagline">${tagline}</p>${featureArtwork(style)}</div><div class="feature-foot">${icon(p)}<div><h4>${esc(p.name)}</h4><p>Alternative to ${esc(p.replaces[0])}</p></div>${svg('arrow','feature-arrow')}</div></a>`).join('')}
</div></section>
<section class="section open-family-section">${heading('Meet the Open family.','More ways to create, work, and make things your own.','#/browse?openOnly=1',`Explore ${projects.filter(p=>p.name.toLowerCase().startsWith('open')).length} Open… apps`)}<div class="apps-grid">${['open-notebook','openpencil','openwhispr','opencloud','opensign','opendesign'].map(id=>row(find(id))).join('')}</div></section>
<section class="section">${heading('Trending repositories','Good projects getting a little more attention.','#/trending','See all','sparkles')}<div class="apps-grid">${trending.map(row).join('')}</div><p class="trend-note">${svg('info')} From GitHub’s weekly Trending page · Snapshot ${date(trendSnapshot.fetchedAt)}</p></section>
<section class="section categories-section">${heading('Find your kind of open.','Something for every part of your day.','#/categories','All categories')}<div class="category-grid">${categories.slice(0,9).map(c=>categoryCard(c)).join('')}</div></section>
<section class="section">${heading('Recently popular','Community favorites worth a closer look.','#/browse?sort=stars','Explore favorites')}<div class="recent-grid">${['appflowy','actual','openobserve'].map(id=>{const p=find(id);return `<article class="recent-card"><a class="recent-cover" href="${appLink(p)}"><img src="assets/${p.screens[0][0]}" alt="${esc(p.screens[0][1])}" loading="lazy" width="500" height="280"></a>${row(p)}</article>`;}).join('')}</div></section>
<section class="section reader-section">${heading('Worth a look. Backed by feedback.','Established apps with published user reviews.','#/browse?reviewed=1&sort=reviews','Browse reviewed apps')}<div class="review-grid">${['openproject','openshot','opencart'].map(id=>reviewCard(find(id))).join('')}</div><p class="review-collection-note">Published ratings and review counts from Capterra · ${date(reviewSnapshot.fetchedAt)} · Ratings cover each listed product, including its hosted or paid editions.</p></section>
<section class="collection-banner"><span class="eyebrow">THE OPEN WORKSPACE COLLECTION</span><h2>A productive day.<br>On your own terms.</h2><p>From notes to project plans, find tools that put you in control of your work.</p><a class="text-link" href="#/browse?category=Productivity">Explore the collection ${svg('arrow')}</a><div class="collection-icons" aria-hidden="true">${['appflowy','openproject','openboard','opentofu'].map(id=>icon(find(id))).join('')}</div></section>
<p class="community-note">${svg('heart')} Built by communities. Discovered by you.</p>`;}
function parseRoute(){const [path='/',query='']=(location.hash.slice(1)||'/').split('?');return {path,params:new URLSearchParams(query)};}
function readFilters(params){return {query:params.get('q')||'',category:params.get('category')||'All',platform:params.get('platform')||'All',minimumStars:params.get('stars')||0,selfHosted:params.get('selfHosted')==='1',trending:params.get('trending')==='1',openOnly:params.get('openOnly')==='1',reviewed:params.get('reviewed')==='1',sort:params.get('sort')||'featured'};}
function sorted(projectList,sort){return [...projectList].sort((a,b)=>sort==='stars'?(b.stars||0)-(a.stars||0):sort==='new'?new Date(b.createdAt)-new Date(a.createdAt):sort==='trending'?(b.weeklyStars||0)-(a.weeklyStars||0):sort==='reviews'?(b.review?.count||0)-(a.review?.count||0):sort==='rating'?(b.review?.rating||0)-(a.review?.rating||0)||(b.review?.count||0)-(a.review?.count||0):sort==='name'?a.name.localeCompare(b.name):0);}
function empty(){return `<div class="empty-state">${svg('search')}<h2>A little too specific?</h2><p>Try another search or give your filters a little more room.</p><button class="button button-primary" data-action="reset-filters">Clear all filters</button><a class="button button-secondary" href="#/">Back to Discover</a></div>`;}
function browse(route){const f=readFilters(route.params);const isTrending=route.path==='/trending',isNew=route.path==='/new';if(isTrending)f.trending=true;const defaultSort=isTrending?'trending':isNew?'new':f.sort;const list=sorted(filterProjects(projects,f),route.params.get('sort')||defaultSort);const resultKey=route.path+'?'+route.params.toString();if(resultKey!==lastResultKey){visibleLimit=24;lastResultKey=resultKey;}const title=f.query?`Results for “${esc(f.query)}”`:f.openOnly?'Open by name. Open by nature.':f.reviewed?'A little more perspective.':isTrending?'A little more attention.':isNew?'New to discover.':f.category!=='All'?`${esc(f.category)}. More open.`:'Find your next favorite app.';const subtitle=isTrending?`Real momentum from GitHub’s weekly Trending page. Snapshot ${date(trendSnapshot.fetchedAt)}.`:isNew?'Fresh projects and new possibilities, sorted by repository creation date.':'Thoughtfully curated alternatives. Find something that feels like you.';
const chips=activeFilters(f,isTrending);const advancedCount=chips.filter(c=>['stars','trending','openOnly','reviewed'].includes(c.key)).length;
return `<section class="explore-intro browse-intro"><div><span class="eyebrow">${isTrending?'TRENDING THIS WEEK':isNew?'FRESH POSSIBILITIES':'THE OPEN COLLECTION'}</span><h1>${title}</h1><p>${subtitle}</p></div></section><section class="browse-controls" aria-label="Browse controls"><div class="browse-toolbar">${searchBox(f.query)}<label class="filter-select platform-select"><select aria-label="Filter by platform" name="platform" data-filter="platform">${['All','macOS','Windows','Linux','Web','iOS','Android'].map(v=>`<option value="${v}" ${f.platform===v?'selected':''}>${v==='All'?'All platforms':v}</option>`).join('')}</select></label><button class="filter-trigger ${advancedCount?'has-filters':''}" data-action="open-filters" aria-haspopup="dialog">${svg('sliders')}Filters${advancedCount?`<span class="filter-count">${advancedCount}</span>`:''}</button><label class="filter-select sort-select"><select aria-label="Sort projects" name="sort" data-filter="sort">${[['featured','Curated'],['stars','Most stars'],['reviews','Most reviews'],['rating','Top rated'],['trending','Momentum'],['new','Newest'],['name','Name A–Z']].map(([v,t])=>`<option value="${v}" ${(route.params.get('sort')||defaultSort)===v?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="category-pills" aria-label="Filter by category">${['All',...categories.map(c=>c.name)].map(c=>`<button class="category-pill ${f.category===c?'active':''}" data-category="${esc(c)}" aria-pressed="${f.category===c}">${c!=='All'?svg(categories.find(x=>x.name===c).icon):svg('layers')}${esc(c==='All'?'All apps':c)}</button>`).join('')}</div></section><div class="results-heading"><div class="results-summary"><strong>${list.length} ${list.length===1?'app':'apps'} to explore</strong><button class="selfhost-toggle" data-action="toggle-selfhost" aria-pressed="${f.selfHosted}">${svg('server')}Self-hosted</button></div>${chips.length?'<button class="text-link" data-action="reset-filters">Reset filters</button>':''}</div>${chips.length?`<div class="active-filters" aria-label="Active filters">${chips.map(c=>`<button data-remove-filter="${c.key}" aria-label="Remove ${esc(c.label)} filter">${esc(c.label)}<span aria-hidden="true">×</span></button>`).join('')}</div>`:''}<div class="catalog-grid" id="results">${list.length?list.slice(0,visibleLimit).map(card).join(''):empty()}</div>${list.length>visibleLimit?`<div class="load-more"><p>Showing ${Math.min(visibleLimit,list.length)} of ${list.length} apps</p><button class="button button-secondary" data-action="load-more">Show more apps ${svg('chevron')}</button></div>`:''}<p class="detail-snapshot">Stars from GitHub · ${date(snapshot.fetchedAt)}. ${isNew?'Repository age does not imply product maturity.':'Comparisons describe overlapping use cases, not feature parity.'}</p>`;}
function activeFilters(f,isTrending=false){return [f.query&&{key:'q',label:`Search: ${f.query}`},f.category!=='All'&&{key:'category',label:f.category},f.platform!=='All'&&{key:'platform',label:f.platform},Number(f.minimumStars)>0&&{key:'stars',label:`${compact(Number(f.minimumStars))}+ stars`},f.selfHosted&&{key:'selfHosted',label:'Self-hosted'},!isTrending&&f.trending&&{key:'trending',label:'Recently trending'},f.openOnly&&{key:'openOnly',label:'Open… apps'},f.reviewed&&{key:'reviewed',label:'With user reviews'}].filter(Boolean);}
function openFilters(){const route=parseRoute(),f=readFilters(route.params),dialog=document.querySelector('#filter-dialog');dialog.querySelector('#filter-options').innerHTML=`<label class="sheet-select"><span>Minimum GitHub stars</span><select name="stars">${[[0,'Any stars'],[1000,'1,000+ stars'],[10000,'10,000+ stars'],[50000,'50,000+ stars'],[100000,'100,000+ stars']].map(([v,t])=>`<option value="${v}" ${Number(f.minimumStars)===v?'selected':''}>${t}</option>`).join('')}</select></label>${[['selfHosted','Self-hosted','Run it on infrastructure you control.'],...route.path==='/trending'?[]:[['trending','Recently trending','On GitHub’s weekly Trending page.']],['openOnly','Open… apps','Projects with names that start with Open.'],['reviewed','With user reviews','Published ratings with a verified source.']].map(([key,label,help])=>`<label class="sheet-check"><span><strong>${label}</strong><small>${help}</small></span><input type="checkbox" name="${key}" ${f[key]?'checked':''}></label>`).join('')}`;dialog.showModal();}

function categoryPage(){return `<section class="explore-intro"><div><span class="eyebrow">YOUR NEXT POSSIBILITY</span><h1>Find your kind of open.</h1><p>From a better workflow to a new creative outlet. Start with what you love.</p></div>${searchBox()}</section><div class="category-directory">${categories.map(c=>categoryCard(c,true)).join('')}</div>${heading('A few community favorites','A good place to begin.','#/browse','All apps')}<div class="apps-grid">${['opencode','open-webui','appflowy','actual','penpot','openproject'].map(id=>row(projects.find(p=>p.id===id))).join('')}</div>`;}
function details(id){const p=projects.find(p=>p.id===id);if(!p)return `<div class="empty-state">${svg('layers')}<h1>That app isn’t in our collection.</h1><p>There are plenty of other possibilities to explore.</p><a class="button button-primary" href="#/">Back to Discover</a></div>`;const related=projects.filter(x=>x.id!==p.id&&x.category===p.category).slice(0,3);const repository=snapshot.repositories?.[p.repo];return `<div class="breadcrumbs"><a href="#/">Discover</a>${svg('chevron')}<a href="#/browse?category=${encodeURIComponent(p.category)}">${esc(p.category)}</a>${svg('chevron')}<span>${esc(p.name)}</span></div><section class="detail-hero">${icon(p)}<div><span class="eyebrow">${esc(p.category)}</span><h1>${esc(p.name)}</h1><p>${esc(p.description)}</p><div class="detail-tags"><span>${p.sourceAvailable?'Source-available':'Open source'}</span><span>·</span><span>${p.selfHosted?'Self-hosting available':'Runs on your device'}</span></div></div><div class="detail-actions"><a class="button button-primary" href="${esc(p.website)}" ${externalAttrs}>Get ${esc(p.name)} ${svg('external')}</a><a class="button button-secondary" href="${gh(p)}" ${externalAttrs}>${svg('github')}GitHub</a><button class="icon-button save-button" data-save="${p.id}" aria-label="${saved.has(p.id)?'Unsave':'Save'} ${esc(p.name)}" aria-pressed="${saved.has(p.id)}" title="${saved.has(p.id)?'Saved to this browser':'Save to this browser'}">${svg('bookmark')}</button></div></section><section class="detail-stats" aria-label="Project information"><div class="detail-stat"><span>GitHub stars</span><strong>${svg('star')}${compact(p.stars)}</strong><small>${exact(p.stars)} stars</small></div><div class="detail-stat"><span>Community forks</span><strong>${svg('fork')}${compact(p.forks)}</strong><small>Open collaboration</small></div><div class="detail-stat"><span>License</span><strong style="font-size:12px">${esc(p.license)}</strong><small>${p.sourceAvailable?'Branding conditions apply':'Read the full license'}</small></div><div class="detail-stat"><span>Platforms</span><strong style="font-size:12px">${esc(p.platforms.slice(0,3).join(' · '))}</strong><small>${p.platforms.length>3?`Also ${esc(p.platforms.slice(3).join(', '))}`:'Find your platform'}</small></div><div class="detail-stat"><span>${p.weeklyStars?'Weekly stars':'Last activity'}</span><strong>${p.weeklyStars?'↗ '+compact(p.weeklyStars):date(p.updatedAt).replace(', 2026','')}</strong><small>${p.weeklyStars?'GitHub trending snapshot':'Repository push date'}</small></div></section>
${p.screens.length?`<section class="screenshot-section"><div class="screenshot-heading"><h2>A closer look.</h2><span>Official project imagery · Click to expand</span></div><div class="screenshot-gallery">${p.screens.map(([file,alt])=>`<button class="screenshot-button" data-image="${esc(file)}" data-caption="${esc(alt)}" aria-label="Expand ${esc(alt)}"><img src="assets/${esc(file)}" alt="${esc(alt)}" width="1000" height="550"></button>`).join('')}</div></section>`:`<section class="product-resource"><div><h3>See ${esc(p.name)} in action.</h3><p>Explore the project’s official website and documentation.</p></div><a class="button button-secondary" href="${esc(p.website)}" ${externalAttrs}>Visit project ${svg('external')}</a></section>`}
${evidence(p)}<div class="detail-body"><section><h2>Meet ${esc(p.name)}.</h2><p>${esc(p.about)}</p><ul>${p.features.map(x=>`<li>${svg('check')}${esc(x)}</li>`).join('')}</ul>${p.note?`<div class="license-note">${esc(p.note)} <a href="${esc(p.licenseUrl||gh(p))}" ${externalAttrs}>Read more ↗</a></div>`:''}<h2 style="margin-top:30px">A fresh alternative.</h2><p>Worth exploring if you use:</p><div class="alternative-chips">${p.replaces.map(x=>`<span>${esc(x)}</span>`).join('')}</div><p style="font-size:10px">These tools share use cases. Features, costs, and deployment needs differ.</p></section><aside class="detail-info"><h3>The details</h3><dl><div><dt>Category</dt><dd><a href="#/browse?category=${encodeURIComponent(p.category)}">${esc(p.category)}</a></dd></div><div><dt>Available on</dt><dd>${esc(p.platforms.join(', '))}</dd></div><div><dt>License</dt><dd><a href="${esc(p.licenseUrl||`${gh(p)}#license`)}" ${externalAttrs}>${esc(p.license)} ↗</a></dd></div><div><dt>Self-hosted</dt><dd>${p.selfHosted?'Available':'Not a hosted server app'}</dd></div><div><dt>Repository</dt><dd><a href="${gh(p)}" ${externalAttrs}>${esc(p.repo)} ↗</a></dd></div><div><dt>Created</dt><dd>${date(p.createdAt)}</dd></div></dl><a class="text-link" href="${esc(p.docs)}" ${externalAttrs}>Read the documentation ${svg('external')}</a><a class="text-link" href="${gh(p)}/issues" ${externalAttrs}>Community & issues ${svg('external')}</a><p class="detail-snapshot">GitHub stats captured ${date(snapshot.fetchedAt)}.</p></aside></div>
${related.length?`<section class="section categories-section">${heading('More possibilities.','Similar tools, the same open spirit.',`#/browse?category=${encodeURIComponent(p.category)}`,'See category')}<div class="apps-grid">${related.map(row).join('')}</div></section>`:''}<a class="back-button" href="#/">${svg('back')}Back to Discover</a>`;}
function render(scroll=true){const route=parseRoute();const oldSearch=document.activeElement?.id==='app-search';const selection=document.activeElement?.selectionStart;const focused=document.activeElement;const filterFocus=focused?.dataset.filter;const actionFocus=focused?.dataset.action;const categoryFocus=focused?.dataset.category;const railLeft=main.querySelector('.category-pills')?.scrollLeft||0;main.innerHTML=route.path.startsWith('/app/')?details(decodeURIComponent(route.path.slice(5))):route.path==='/categories'?categoryPage():route.path==='/'?home():browse(route);document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(route.path==='/categories'?'categories':route.path==='/trending'?'trending':route.path==='/new'?'new':route.path.startsWith('/app/')||route.path==='/browse'?'':'discover')));const p=projects.find(p=>route.path==='/app/'+p.id);document.title=p?`${p.name} — OpenStore`:route.path==='/categories'?'Categories — OpenStore':route.path==='/trending'?'Trending — OpenStore':route.path==='/new'?'New — OpenStore':'OpenStore — Great software. Open possibilities.';if(oldSearch&&!scroll){const input=document.querySelector('#app-search');if(input){input.focus();try{input.setSelectionRange(selection,selection);}catch{}}}const rail=main.querySelector('.category-pills');if(rail){rail.scrollLeft=railLeft;rail.querySelector('.active')?.scrollIntoView({block:'nearest',inline:'nearest'});}if(!scroll&&!oldSearch){const target=filterFocus?main.querySelector(`[data-filter="${filterFocus}"]`):actionFocus?main.querySelector(`[data-action="${actionFocus}"]`):categoryFocus?main.querySelector(`[data-category="${CSS.escape(categoryFocus)}"]`):null;target?.focus({preventScroll:true});}if(scroll)window.scrollTo({top:0,behavior:'instant'});}
function updateFilter(key,value,{replace=false}={}){const route=parseRoute();const path=route.path==='/'||route.path==='/categories'||route.path.startsWith('/app/')?'/browse':route.path;const params=route.params;if(value===null||value===''||value==='All'||value==='0')params.delete(key);else params.set(key,value);const hash=`#${path}${params.size?'?'+params.toString():''}`;if(replace){history.replaceState(null,'',hash);render(false);}else{history.pushState(null,'',hash);render(false);}}
function toast(message){const box=document.querySelector('#toast');box.textContent=message;box.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove('visible'),2600);}
main.addEventListener('input',e=>{if(e.target.id==='app-search')updateFilter('q',e.target.value,{replace:true});});
main.addEventListener('change',e=>{if(e.target.dataset.filter){updateFilter(e.target.dataset.filter,e.target.type==='checkbox'?(e.target.checked?'1':null):e.target.value);}});
main.addEventListener('click',e=>{const category=e.target.closest('[data-category]');if(category){updateFilter('category',category.dataset.category);return;}const search=e.target.closest('[data-search]');if(search){location.hash='/browse?q='+encodeURIComponent(search.dataset.search);return;}const remove=e.target.closest('[data-remove-filter]');if(remove){updateFilter(remove.dataset.removeFilter,null);main.querySelector('[data-action="open-filters"]')?.focus({preventScroll:true});return;}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='open-filters'){openFilters();return;}if(action==='toggle-selfhost'){updateFilter('selfHosted',readFilters(parseRoute().params).selfHosted?null:'1');return;}if(action==='load-more'){visibleLimit+=24;render(false);main.querySelectorAll('.catalog-card')[visibleLimit-24]?.querySelector('a')?.focus({preventScroll:true});}if(action==='reset-filters'){const r=parseRoute();history.pushState(null,'',r.path==='/trending'?'#/trending':r.path==='/new'?'#/new':'#/browse');render(false);}if(action==='clear-search'){updateFilter('q','',{replace:true});document.querySelector('#app-search')?.focus();}const image=e.target.closest('[data-image]');if(image){const dialog=document.querySelector('#image-dialog');dialog.querySelector('img').src='assets/'+image.dataset.image;dialog.querySelector('img').alt=image.dataset.caption;dialog.querySelector('p').textContent=image.dataset.caption;dialog.showModal();}const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;if(saved.has(id))saved.delete(id);else saved.add(id);try{localStorage.setItem('openstore-saved',JSON.stringify([...saved]));}catch{}save.setAttribute('aria-pressed',saved.has(id));save.setAttribute('aria-label',`${saved.has(id)?'Unsave':'Save'} ${projects.find(p=>p.id===id).name}`);toast(saved.has(id)?'Saved to this browser.':'Removed from saved apps.');}});
window.addEventListener('hashchange',()=>render());
window.addEventListener('popstate',()=>render());
function focusSearch(){if(!document.querySelector('#app-search')){history.pushState(null,'','#/browse');render();}document.querySelector('#app-search')?.focus();}
document.querySelector('.skip-link').addEventListener('click',e=>{e.preventDefault();main.focus();main.scrollIntoView();});
document.querySelector('#search-shortcut').innerHTML=svg('search');document.querySelector('#search-shortcut').addEventListener('click',focusSearch);
document.querySelector('#github-nav').insertAdjacentHTML('afterbegin',svg('github'));
const themeToggle=document.querySelector('#theme-toggle');
function updateThemeControl(){const dark=document.documentElement.dataset.theme==='dark';const label=`Switch to ${dark?'light':'dark'} mode`;themeToggle.innerHTML=svg(dark?'sun':'moon');themeToggle.setAttribute('aria-label',label);themeToggle.title=label;document.querySelector('meta[name="theme-color"]').content=dark?'#101113':'#ffffff';}
themeToggle.addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('openstore-theme',theme);}catch{}updateThemeControl();});
updateThemeControl();
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();focusSearch();}if(e.key==='Escape'&&document.activeElement?.id==='app-search'){document.activeElement.blur();}});
document.querySelector('#about-button').addEventListener('click',()=>document.querySelector('#about-dialog').showModal());
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}});});
document.querySelector('#filter-form').addEventListener('submit',e=>{e.preventDefault();const dialog=document.querySelector('#filter-dialog'),data=new FormData(e.target),route=parseRoute();for(const key of ['stars','selfHosted','trending','openOnly','reviewed']){if(key==='trending'&&route.path==='/trending')continue;const value=data.get(key);if(value&&value!=='0')route.params.set(key,key==='stars'?value:'1');else route.params.delete(key);}dialog.close();history.pushState(null,'',`#${route.path}${route.params.size?'?'+route.params.toString():''}`);render(false);main.querySelector('[data-action="open-filters"]')?.focus({preventScroll:true});});
document.querySelector('#clear-advanced-filters').addEventListener('click',()=>{document.querySelector('#filter-form').reset();document.querySelector('#filter-form select').value='0';document.querySelectorAll('#filter-form input').forEach(input=>input.checked=false);});
async function loadJSON(path){const response=await fetch(path);if(!response.ok)throw new Error(`Unable to load ${path}`);return response.json();}
try {
 const loaded=await Promise.allSettled([loadJSON('assets/github-snapshot.json'),loadJSON('assets/trending-snapshot.json'),loadJSON('assets/asset-sources.json'),loadJSON('assets/official-icons.json'),loadJSON('assets/reviews-snapshot.json')]);
 snapshot=loaded[0].status==='fulfilled'?loaded[0].value:{};trendSnapshot=loaded[1].status==='fulfilled'?loaded[1].value:{};assetSources=loaded[2].status==='fulfilled'?loaded[2].value:{};officialIcons=loaded[3].status==='fulfilled'?loaded[3].value:{};reviewSnapshot=loaded[4].status==='fulfilled'?loaded[4].value:{};
 if(projects.some(p=>!officialIcons[p.id]?.file))throw new Error('Official project icons are unavailable.');
 projects=projects.map(p=>{const stats=snapshot.repositories?.[p.repo];const trend=trendSnapshot.repositories?.find(t=>t.repo.toLowerCase()===p.repo.toLowerCase());return {...p,review:reviewSnapshot.projects?.[p.id],bestFor:p.bestFor||reviewSnapshot.projects?.[p.id]?.useCase,stars:stats?.stargazers_count,forks:stats?.forks_count,updatedAt:stats?.pushed_at,createdAt:stats?.created_at,trending:!!trend,weeklyStars:trend?.weeklyStars,screens:p.screens.filter(([file])=>assetSources[file]&&!assetSources[file].error)};});
 document.querySelector('#snapshot-info').textContent=`Repository metadata: ${date(snapshot.fetchedAt)}. All ${projects.length} apps use official project icons. Screenshots are sourced from official repositories and websites.`;
 render();
} catch(error){main.innerHTML=`<div class="empty-state"><h2>Let’s try that again.</h2><p>The collection couldn’t load. Refresh to try again.</p><button class="button button-primary" onclick="location.reload()">Refresh OpenStore</button></div>`;console.error(error);}
